project:
  type: website
  output-dir: docs

website:
  title: "Trajectories"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    fontsize: smaller
    max-width: 600px
    css: styles.css